includeDir = -I "C:/Users/Prayas Meher/Andromeda/Andromeda/include" -I "C:/Users/Prayas Meher/Andromeda/vendor/spdlog/include"
libDir = lib/

all:
	g++ $(includeDir) -L $(libDir) -o Sandbox2D Sandbox2D.cpp -lmingw32 -lAndromeda